// from https://github.com/sublimehq/Packages/blob/master/Haskell/Haskell.sublime-syntax
#set raw(syntaxes: "Haskell.sublime-syntax")
// modified few lines from above with same highlighting (no actual syntax modification)
#set raw(syntaxes: "ghci.sublime-syntax")
// https://github.com/LogtalkDotOrg/logtalk3/blob/master/coding/sublimetext/Logtalk.sublime-syntax
#set raw(syntaxes: "Logtalk.sublime-syntax")
// modified few lines from above with same highlighting (no actual syntax modification)
#set raw(syntaxes: "Prolog.sublime-syntax")

#import "@preview/ilm:2.1.1": *

// ==================== 한글 폰트 설정 ====================
#let font-serif = "Noto Serif CJK KR"
#let font-sans = "Noto Sans CJK KR"
#let font-mono = "DejaVu Sans Mono"

#set text(font: font-serif, size: 11pt, lang: "ko", region: "KR")

// #set heading(numbering: "1.", depth: 3) // 이건 ilm 없을 때
#show heading: set text(font: font-serif)

// 한국어 section numbering style
#show heading: set heading(supplement: [§#h(-0.3em)]) // -공백 간격 조절
#show figure.where(kind: image): set figure(supplement: [그림])
#show figure.where(kind: table): set figure(supplement: [표])


#import "braid/lib.typ": setup
// #import "@local/braid:0.1.0": setup // after localinstall.sh, this will work

#let braid = setup(config: (
  files-db: json("files.json"), // generated by top-level Makefile
  build-dir: "_build", // dir for source/input/output files
  typfile-path: "../main.typ", // main.typ path from generated _build/Makefile
  tag-stdioe-cmd: "python ../tag-stdioe.py", // command used by generated _build/Makefile
))

#let get-extension(lang) = (braid.get-extension)(lang)
#let count-lines(code-str) = (braid.count-lines)(code-str)

#let snippet-break-str = braid.snippet-break-str

#let join-lines(lang) = (braid.join-lines)(lang)
#let join-str(lang) = (braid.join-str)(lang)

#let code(file: none, visible: true, output-render: none, body) = (braid.code)(file: file, visible: visible, output-render: output-render, body)

#let read-raw(path, lang: none, block: true, preprocess: none) = (braid.read-raw)(path, lang: lang, block: block, preprocess: preprocess)

#(braid.init)()


#show: ilm.with(
  title: [
    #text(size: 24pt)[Theory of Computation @ HNU CE (2026년 2학기)]
  ],
  authors: "kya",
  date-format: "[year]-[month]-[day]",
  date: datetime.today(),
  abstract: none,
  table-of-contents: none,
  raw-text: (font: font-mono, size: 10.5pt, ligatures: false),
  chapter-pagebreak: false,
)

#show raw: set text(font: font-mono, size: 10.5pt, ligatures: false)

////////////////////////////////////////////////////////////////////////////

= 주교재 Ch.0. Introduction
가나다라

= Second Section
마바사

#code(file: "hello.pl")[```prolog
app([], L, L).
app([H|L1], L2, [H|L]) :- app(L1, L2, L).

?- app(L1, L2, [1,2]),
   format("L1 = ~w, L2 = ~w~n", [L1, L2]).
```]


#code(file: "hello.pl")[```prolog
?- findall( (L1,L2), app(L1, L2, [1,2,3]), Bag ),
   forall( member((L1,L2), Bag),
           format("L1 = ~w, L2 = ~w~n", [L1, L2]) ).
```]


#code(file: "hello.pl")[```prolog
?- findnsols( 2,
              (L1,L2), app(L1, L2, [1,2,3]), Bag ),
   forall( member((L1,L2), Bag),
           format("L1 = ~w, L2 = ~w~n", [L1, L2]) ).
```]




= Third Section
아자차카
타파하


