// from https://github.com/sublimehq/Packages/blob/master/Haskell/Haskell.sublime-syntax
#set raw(syntaxes: "Haskell.sublime-syntax")
// modified few lines from above with same highlighting (no actual syntax modification)
#set raw(syntaxes: "ghci.sublime-syntax")
// https://github.com/LogtalkDotOrg/logtalk3/blob/master/coding/sublimetext/Logtalk.sublime-syntax
#set raw(syntaxes: "Logtalk.sublime-syntax")
// modified few lines from above with same highlighting (no actual syntax modification)
#set raw(syntaxes: "Prolog.sublime-syntax")

#import "@preview/ilm:2.1.1": *

// ==================== 한글 폰트 설정 ====================
#let font-serif = "Noto Serif CJK KR"
#let font-sans = "Noto Sans CJK KR"
#let font-mono = "DejaVu Sans Mono"

#let sc(body) = text(
  font: "Libertinus Serif",
  features: ("smcp",)
)[#body]

#let uline(w) = box(baseline: 0pt)[#line(length: w, stroke: 0.7pt)]

#let mathit(word) = text(font: "New Computer Modern", style: "italic")[#word]

// #set heading(numbering: "1.", depth: 3) // 이건 ilm 없을 때
#show heading: set text(font: font-serif)

// 한국어 section numbering style
#show heading: set heading(supplement: [§#h(-0.3em)]) // -공백 간격 조절
#show figure.where(kind: image): set figure(supplement: [그림])
#show figure.where(kind: table): set figure(supplement: [표])


#import "braid/lib.typ": setup
// #import "@local/braid:0.1.0": setup // after localinstall.sh, this will work

#let braid = setup(config: (
  files-db: json("files.json"), // generated by top-level Makefile
  build-dir: "_build", // dir for source/input/output files
  typfile-path: "../main.typ", // main.typ path from generated _build/Makefile
  tag-stdioe-cmd: "../tag-stdioe.py", // command used by generated _build/Makefile
))

#let get-extension(lang) = (braid.get-extension)(lang)
#let count-lines(code-str) = (braid.count-lines)(code-str)

#let snippet-break-str = braid.snippet-break-str

#let join-lines(lang) = (braid.join-lines)(lang)
#let join-str(lang) = (braid.join-str)(lang)

#let code(file: none, visible: true, output-render: none, body) = (braid.code)(file: file, visible: visible, output-render: output-render, body)

#let read-raw(path, lang: none, block: true, preprocess: none) = (braid.read-raw)(path, lang: lang, block: block, preprocess: preprocess)

#(braid.init)()


#set page(paper: "a4", flipped: false, margin: (x: 1.5cm, y: 1.2cm))
#set text(font: font-serif, size: 18pt, lang: "ko", region: "KR")
#show raw: set text(font: font-mono, size: 14pt, ligatures: false)

#show: ilm.with(
  title: [
    #text(size: 24pt)[Theory of Computation @ HNU CE (2026년 2학기)]
  ],
  authors: "kya",
  date-format: "[year]-[month]-[day]",
  date: datetime.today(),
  abstract: none,
  // table-of-contents: none,
  raw-text: (font: font-mono, size: 10.5pt, ligatures: false),
  chapter-pagebreak: false,
)

#set page(paper: "a4", flipped: false, margin: (x: 1.5cm, y: 1.2cm))
#set text(font: font-serif, size: 12pt, lang: "ko", region: "KR")
#show raw: set text(font: font-mono, size: 10.5pt, ligatures: false)


///////////////////////////////////////////////////////////////////
#heading(level: 1, numbering: none)[HW01 함수(function)와 관계(relation)의 항수(arity)]
- 이름: 
- 학번: 
#v(0.5em)
#heading(level: 2, numbering: none)[주교재 Example 0.9]
예제(Example)의 2항 함수(binary function)
$g: cal(Z)_4 times cal(Z)_4 arrow cal(Z)_4$에 해당하는 \
관계(relation)를 `g`를 정의한다면 그 관계의 항수는 얼마일지 생각해 보고, \
이 관계 `g`를 Prolog 술어(predicate)로 정의하여 두 개 이상의 쿼리를 작성해 보라.

(1) `g`의 항수(arity)는? $quad$ 답: #uline(5em)

(2) 관계 정의 코드와 쿼리를 아래에 작성하고 문서를 make로 빌드하여 실행 결과 확인.
#code(file: "TC26hw01.pl")[```prolog
% 여기에 g(...). 코드 작성

?- true,                    % 이 줄의 true 대신 적절한 첫째 쿼리 작성
   format('~w ~w!~n', ['1st','result']). % 적절한 형식으로 결과 출력
?- true,                    % 이 줄의 true 대신 적절한 첫째 쿼리 작성
   format('~w ~w!~n', ['2nd','result']). % 적절한 형식으로 결과 출력
```]

#pagebreak()
- 이름: 
- 학번: 
#heading(level: 2, numbering: none)[주교재 Example 0.10]
예제(Example)의 판별 함수(조건 함수, predicate, property)
#mathit("beats")에 해당하는 \
관계 `beats`를 정의한다면 그 관계의 항수는 얼마일지 생각해 보고, \ 
마찬가지로 `beats`를 Prolog로 정의하여 두 개 이상의 쿼리를 작성해 보라.

(1) `beats`의 항수(arity)는? $quad$ 답: #uline(5em)

(2) 관계 정의 코드와 쿼리를 아래에 작성하고 문서를 make로 빌드하여 실행 결과 확인.
#code(file: "TC26hw01.pl")[```prolog
% 여기에 beats(...). 코드 작성
% 단, Prolog에서 대문자는 변수로 취급되므로
% scissors, paper, stone 이렇게 소문자로 코드에 작성할 것

?- true,                    % 이 줄의 true 대신 적절한 첫째 쿼리 작성
   format('~w ~w!~n', ['1st','result']). % 적절한 형식으로 결과 출력
?- true,                    % 이 줄의 true 대신 적절한 첫째 쿼리 작성
   format('~w ~w!~n', ['2nd','result']). % 적절한 형식으로 결과 출력
```]

///////////////////////////////////////////////////////////////////
#set page(paper: "a4", flipped: true, margin: (x: 1.5cm, y: 1.2cm))
#set text(font: font-serif, size: 18pt, lang: "ko", region: "KR")
#show raw: set text(font: font-mono, size: 14pt, ligatures: false)
#pagebreak()

= Prolog 소개

Prolog 코드에서`%`로 시작해 줄 끝까지 부분은 주석(comment)으로 취급됨.

== 가족 관계 예시

#code(file: "family.pl")[```prolog
% 1항 관계 male    원소나열법 표현
male('bob').      male('john').     % 원래 한줄에 하나씩 작성을 권장
% 1항 관계 female  원소나열법 표현
female('alice').  female('carol').  % 원래 한줄에 하나씩 작성을 권장
% 2항 관계 child.  원소나열법 표현
child('bob', 'alice').  child('carol', 'alice').
child('bob', 'john').   child('carol', 'john').
% 2항 관계 son     조건제시법 표현
son(X, Y) :- child(X, Y), male(X).

?- findall( (X,Y), son(X, Y) , Bag ),
   forall( member((X,Y), Bag), 
           format("son: X = ~w, Y = ~w~n", [X, Y]) ).
```]

#pagebreak()
== 리스트 기초, 출력을 위한 술어, 연결자(connective) 우선순위
Prolog에서 리스트(list)는
- 길이 0인 빈 리스트는 `[]`로 표현
- `[1,2,3]`처럼 쉼표(`,`)로 구분하여 나열한 원소를 대괄호(`[`와 `]`)로 감싸서 표현
- `[H|T]`처럼 하나의 원소(`H`, 머리)와 나머지 리스트(`T`, 꼬리)로 나누어 표현

```
                                             /`\          
    [ 1,  2,  3       ] =                   1   `\        
    [ 1| [2,  3     ] ] =                        /`\      
    [ 1| [2| [3   ] ] ] =                       2   `\    
    [ 1| [2| [3|[]] ] ]                              /`\  
                                                    3  [] 
```

실제로 `write` 술어(predicate)로 출력해 보면 똑같다.
#code(file: "listbasic.pl")[```prolog
?- L = [ 1,  2,  3       ], write(L), nl.
?- L = [ 1| [2,  3     ] ], write(L), nl.
?- L = [ 1| [2| [3   ] ] ], write(L), nl.
?- L = [ 1| [2| [3|[]] ] ], write(L), nl.
```]

Prolog에서는 `조건 -> 참인_경우 ; 거짓인_경우` 형태로 if-then-else를 표현 가능
#code(file: "listbasic.pl")[```prolog
?- [1,2,3] = [1,[2,3]]  -> (write(true), nl) ; (write(false), nl).
?- [1,2,3] = [1|[2,3]]  -> (write(true), nl) ; (write(false), nl).
```]

and 연결자(`,`)의 우선순위가 if 연결자(`->`)와 or 연결자(`;`)보다 높으므로 괄호 생략 가능
#code(file: "listbasic.pl")[```prolog
?- [1,2,3] = [1,[2,3]]  ->  write(true), nl  ;  write(false), nl .
?- [1,2,3] = [1|[2,3]]  ->  write(true), nl  ;  write(false), nl .
```]

하나의 파일 `listbasic.pl`을 이렇게 여러 부분의 코드 조각으로
나누어 작성하는 것도 가능하다.

좀 더 복잡한 형식의 출력은 C의 printf와 비슷한 `format` 술어를 활용
#code(file: "listbasic.pl")[```prolog
?- L1 = [1], L2 = [2,3], format("L1 = ~w, L2 = ~w", [L1,L2]).
```]

#pagebreak()
== 리스트 연결 예시

`app(L1,L2,L)`은 두 리스트 `L1`과 `L2`를 이어붙이면 `L`이 되는 3항 관계
#code(file: "listapp.pl")[```prolog
app([], L, L).                             % 빈 리스트와 L을 연결하면 L
app([H|L1], L2, [H|L]) :- app(L1, L2, L).  % 길이 1이상의 리스트와 L2 연결하는 재귀적 규칙

?- app([1], [2,3], L),       % 관계를 만족하는 L을 탐색
   format("L = ~w~n", [L]).  % L을 적절한 형식으로 출력
```]

원래 `app`을 정의할 때 생각했던 것과 반대 방향으로도 활용 가능! \
- `L1`과 `L2`를 연결해 `L`이 되는 관계를 생각하고 정의했는데 ... \
- 반대로 `L`을 `L1`과 `L2`로 나누는 방법도 탐색 가능!!!
(참고로, 이런 반대 방향 탐색이 모든 정의에 대해 항상 잘 되는 것은 아님)

#code(file: "listapp.pl")[```prolog
?- app(L1, L2, [1,2,3]),      % 관계를 만족하는 1가지 경우를 찾아서
   format("L1 = ~w, L2 = ~w~n", [L1, L2]). % 적절한 형식으로 출력
```]

길이 0인 `L1`인 당연한 경우만 탐색되어 실망했다면 ... 다음 페이지를 보라

#pagebreak()
`app(L1,L2,[1,2,3])`를 만족하는 모든 경우를 탐색하려면 `findall`을 활용해 질의(query)
#code(file: "listapp.pl")[```prolog
?- findall( (L1,L2), app(L1, L2, [1,2,3]), Bag ),  % 모든 경우의 집합 Bag
   forall( member((L1,L2), Bag),  % 모든 경우를 순회하며 Bag의 원소 [L1,L2]를 하나씩
           format("L1 = ~w, L2 = ~w~n", [L1, L2]) ).        % 적절한 형식으로 출력
```]

최대 몇 개까지만 찾으려면 `findsols`를 활용해 질의(query)
#code(file: "listapp.pl")[```prolog
?- findnsols( 2,  % 최대 2개까지만 만족하는 해를 찾기
              (L1,L2), app(L1, L2, [1,2,3]), Bag ),
   forall( member((L1,L2), Bag),
           format("L1 = ~w, L2 = ~w~n", [L1, L2]) ).
```]

#pagebreak()
== 사실(fact), 규칙(rule), 절(clause), 술어(predicate)

술어(predicate)
- 일반적으로 관계(relation)를 정의함
- 하나 이상의 절(clause)로 구성됨

절(clause)은 다음 두 형태 중 하나
- 사실(fact)
  - 머리(head) 부분 다음에 `:-` 없이 `.`으로 끝나는 형태
  - 머리 부분이 나타내는 성질이 아무런 조건 없이 항상 참
- 규칙(rule)
  - 머리(head) 부분 다음 `:-`와 몸체(body) 부분이 오고 `.`로 끝나는 형태
  - 머리 부분이 나타내는 성질이 특정 조건(즉, 몸체가 나타내는 성질)이 성립할 때만 참

```prolog
%% 사실들만으로 정의된 술어 male
male(bob).
male(john).
%% 규칙 하나로만 정의된 술어 father
father(X) :- child(C,X), male(X).    % 자녀가 있고 남자인 조건이 성립해야 아버지로 인정

%% 사실과 규칙 각각 하나씩 2개의 절로 정의된 술어 is_list
is_list([]).                  % 사실(fact): []는 무조건 리스트로 인정
is_list([H|T]) :- is_list(T). % 규칙(rule): [H|T]는 is_list(T)가 성립해야 리스트로 인정
```

사실(fact)을 똑같은 의미의 규칙(rule) 형태로 바꿔 쓰려면 \
머리 다음에 바로 `.`으로 끝내는 대신 뒤에 `:- true.`라고 쓰면 됨.

```prolog
male(bob)  :- true.  % male(bob). 과 똑같은 의미
make(jonh) :- true.  % male(bob). 과 똑같은 의미
```

왜냐하면 `true`는 무조건 참으로 Prolog에서 미리 정의된 특별한 술어이기 때문.

~

Prolog의 규칙 형태의 절 $C$ `:-` $P_1$`,` $P_2$`,` ... `,` $P_n$`.` 는
#v(5mm)
추론규칙
$display(frac(P_1 quad P_2 quad ... quad P_n, C))$ 혹은
논리식 
$P_1 and P_2 and ... and P_n ==> C$ 에 해당한다. 


#pagebreak()
== 항(term)과 일치화(unification)

~

=== 항(term)
Prolog에서 술어(predicate)가 뭔가 실행되어 움직이는 동적인 무언가라면, \
항(term)은 정적인 데이터에 해당한다.

항(term)은 다음 셋 중 하나의 형태
- 변수(variable): `X`, `Y1` 처럼 대문자로 시작
- 상수(constant)
  - atom: `a`, `b1`처럼 소문자로 시작하거나 `'Hello World'` 처럼 따옴표로 둘러싸인 것
  - number: `123`같은 정수나 `3.14`같은 실수
- compound term / structure: `f(t1, ...)`
  - 여기서 `f`는 함수자(functor) / 함수 기호(function symbol)
  - 여기서 `t1`, ... 등등은 항(term)


functor의 항수(arity)
- `f(t1,t2)`에서 `f`의 항수는 2
- `f(t1,t2,t3)`에서 `f`의 항수는 3
프로그램 코드에서는 같은 `f`지만
Prolog 내부적으로 전자는 `f/2`, 후자는 `f/3`와 같이 처리해
위의 두 `f`를 서로 다른 functor로 확실히 구분함!!!
(`g`, `h`, `f1`, `f4`처럼 이름이 다른 경우나 마찬가지)


=== 일치화(unification)

일치화(unification)란 두 항(term)을 서로 동일하게 만들 수 있는지 판단하는 과정이다.
그 과정에서 필요하다면 변수를 항으로 치환(substitute)함으로써
(혹은, 변수에 항을 대입함으로써) 두 항을 동일하게 만든다.

변수가 없는 경우에는 단순히 판단하기만 하면 됨
#code(file: "unification.pl")[```prolog
?- a = 3 -> write(true), nl ; write(false), nl.
?- a = a -> write(true), nl ; write(false), nl.
```]

#code(file: "unification.pl")[```prolog
?- f(1,3) = g(1,3) -> write(true), nl ; write(false), nl.
?- f(1,a) = f(1,3) -> write(true), nl ; write(false), nl.
?- f(1,3) = f(1,3) -> write(true), nl ; write(false), nl.
```]

#pagebreak()
변수에 무엇을 대입해도 일치화할 수 없는 경우들
#code(file: "unification.pl")[```prolog
?- f(1,a) = f(X,3) -> format('success: X = ~w~n', [X])
                    ; format("failure~n").
?- f(1,Y) = g(X,3) -> format('success: X = ~w, Y = ~w~n', [X,Y])
                    ; format("failure~n").
```]

변수를 적절히 치환하여 일치화에 성공하는 경우들
#code(file: "unification.pl")[```prolog
?- f(1,3) = f(X,3) -> format('success: X = ~w~n', [X])
                    ; format("failure~n").
?- f(1,Y) = f(X,3) -> format('success: X = ~w, Y = ~w~n', [X,Y])
                    ; format("failure~n").
```]

살펴본 바와 같이 Prolog는 항(term)에 대한 일치화(unification) 알고리즘을
자체적으로 내장하고 있으므로, Prolog에서 제공하는 두 항의 일치화 기능을
위헤 제공하는 특수한 2항 술어(predicate)인 `=`를 사용하기만 하면 됨.


//////////////////////////////////////////////////////////////////
#pagebreak()

#heading(level: 1, numbering: none)[주교재 0 Introduction]
주교재에서 다루는 영역에 대한 개괄적 소개.

주교재에서 설명하면서 필요한 수학적 개념들 미리 정리.

#heading(level: 2, numbering: none)[주교재 0.1 오토마타, 계산가능성, 복잡도]

계산이론(theory of computation)이 다루는 세 가지 영역
- 오토마톤 / 상태 기계: Automaton / State Machine
- 계산가능성: Computability - 어떤 문제가 계산으로 정의/해결 가능한지
- (계산)복잡도: (Computational) Complexity - 계산하기 위해 필요한 자원 소모 정도

참고로 오토마타(Automata)는 오토마톤(Automaton)의 복수형. \
근데 한국어에서는 귀찮으니 그냥 1개도 오토마타라고 부르는 경우가 많음. \
영어로 쓸 때는 주의해야 함.


계산이론의 이런 모든 분야를 관통하는 핵심 질문: \
#quote[
  What are the fundamental capabilities and limits of computation?
] \
#quote[
  계산이라는 절차가 근본적인 역량과 한계는 무엇인가?
]

즉, 계산이라는 것으로 어디까지는 할 수 있고 어떤 범위에서는 계산이라는 것이 불가능한지 탐구하는 것이 계산이론의 핵심이다.

(계산할 수 있을 거 같은데 ... 안되는 것도 있다는 이야기)

#heading(level: 3, numbering: none)[Complexity Theory 복잡도 이론]
계산의 난이도를 다루는 이 분야의 핵심 질문: \
#quote[
  What makes some problems computationally hard and others easy?
] \
#quote[
  어떤 문제들은 계산적으로 어렵고 다른 문제들은 쉬운 것은 무엇 때문인가?
]

알고리즘 과목에서 많이 다루는 개념. (근데 일단 계산이 가능한 것들 중에서 ...)

#heading(level: 3, numbering: none)[Computability Theory 계산가능성 이론]
이 분야의 선구자들: 쿠르트 괴델, 앨런 튜링, 알론조 처치

이 이론을 전개하기 위해서는 계산이 무엇인지 정의해야 함

계산의 모델(model)이라는 것을 정의하는 방식으로 계산이 무엇인지 정의함

#heading(level: 3, numbering: none)[Automata Theory 오토마타 이론]
계산이 무엇인지 정의하는 한 방식으로 활용됨. 계산의 모델을 명확히 제시해야 계산이 가능한지,
가능하다면 그 계산이 얼마나 어려운지(필요 시간, 공간 등 자원) 판단 가능.

여러 모델들이 다른 분야에서도 응용됨
- 유한 오토마타 / 유한 상태 기계: Finite Automata / Finite State Machine \ - 텍스트 처리, 컴파일러에서 어휘 분석, 등등
- 푸시다운 오토마타 / 스택 오토마타: Pushdown Automata / Stack Automata \ - 언어의 문법 분석, 등등

#heading(level: 2, numbering: none)[주교재 0.2 수학적 표기법과 용어]
#heading(level: 3, numbering: none)[집합 set]
집합(set)은 원소/멤버(element/member)들의 모임.

집합의 원소나열법 표기: $S = {7,12,57}$

원소와 집합의 포함 관계 표현: ~ $7 in S$, ~ $8 in.not S$

원소나열법과 생략 기호를 활용한 표기:
- $cal(N) = {0, 1, 2, ...}$  ~~~~ (자연수의 집합)
- $cal(Z) = {..., -2, -1, 0, 1, 2, ...}$  ~~ (정수의 집합)

집합의 조건제시법 표기(set-builder notation): $S = {m^2 mid(|) m in cal(N) }$ ~~ (자연수의 집합)

공집합: $emptyset = {}$ ~~ (원소가 하나도 없는 빈 집합)

원소가 딱 1개인 "한원소 집합"(singleton set). ~ 예: ${7}$ ~~ (원소가 7 하나뿐인 집합)

원소가 딱 2개인 집합을 "순서 없는 쌍"(unordered pair) 또는 "집합쌍"이라고 함. \
예: ${7, 12} = {12, 7}$ ~~ (원소가 7과 12뿐인 집합)

순서쌍(ordered pair, pair, 2-tuple). ~ 예: $(7, 12) eq.not (12, 7)$  ~~ (순서가 중요) \
일반적으로 $k$-tuple.  예: $(7, 12, 5)$ ~~ (3-tuple)

집합의 연산
- 교집합(intersection): $A inter B$
- 합집합(union): $A union B$
- 여집합(complement): $overline(A) = {x mid(|) x in U, x in.not A}$ ~ 전체집합($U$)이 정의되어 있어야 함
- 곱집합(cartesian product): $A times B = {(x,y) mid(|) x in A, y in B}$
- 멱집합(power set): $cal(P)(A) = 2^A = {B mid(|) B subset.eq A}$

집합 3개를 연속해서 곱집합(cartesian product)하면 3-tuple들의 집합이 만들어짐:
$A times B times C = {(x,y,z) mid(|) x in A, y in B, z in C}$\
이런 식으로 정의되는 3-tuple에서는 $(a,b,c) = ((a,b),c) = (a,(b,c))$를 동치로 취급함.
즉, $(A times B) times C = A times (B times C) = A times B times C$ 라는 말.
하지만, 경우에 따라서는 이걸 구분해서 다루기도 하므로 주의가 필요. 맥락을 잘 살펴야.

벤다이어그램(Venn diagram)은 주교재 그림 참고

집합의 거듭제곱 표기
- $A^1 = A$
- $A^2 = A times A$
- $A^3 = A times A times A$
- ...
일반적으로 $A^(k+1) = A times A^k$

그런데 $A^0$ 은 무엇이 되어야 할까? 일단, 공집합($emptyset$)은 안됨!

유한집합의 경우 $A times B$의 크기(원소의 개수)는 각각의 크기(원소의 개수)의 곱. \
한쪽 크기가 0이면 곱집합의 크기도 0이 됨. 따라서, $A^0$은 한원소 집합이어야 함. \
근데, 그 한 원소를 뭘로 하지?

$A^0 = {()}$ ~~ (한원소 집합, 그 한 원소 $()$는 0-tuple)


$A = {a_1, a_2, ...} = {(a_1),(a_2), ...}$

원소 $a_i$ 와 그 원소 하나만으로 이루어진 1-tuple $(a_i)$는 동치로 취급.\
또한 $((),a_i) = (a_i) = (a_i,())$ 이것들도 모두 동치로 취급.

$A^0 times A^1 = {()} times {a_1,a_2,...} = {(a_1),(a_2),...}$

#heading(level: 3, numbering: none)[함수와 관계 functions and relations]

함수(function)는 각 원소를 빠짐없이 정확히 하나씩의 원소에 일대일로 대응시키는 관계.\
대응되는 대상 자체는 겹쳐도 됨. $x_1 eq.not x_2$ 이더라도 $f(x_1) = f(x_2)$ 일 수 있음.

같은 $x$를 서로 다른 원소에 대응시키면 안 됨.
$f(x) = y_1 eq.not y_2 = f(x)$ 이면 $f$는 함수가 아님.

빠지는 게 있어도 안됨. $A = {1,2,3}$일 때, 함수 $f: A arrow B$를
순서쌍의 집합으로 표현했을 때\
$f = {(1,b_1), (3,b_3)}$ 인 경우 함수가 아님. (원소 2가 대응 안됨) \
이렇게 일대일 조건을 만족하면 부분함수(partial function).
이런 부분함수에 해당하는 구조를 데이터구조 이론이나
프로그래밍언어 라이브러리에서 딕셔너리(dictionary) 또는 맵(map)이라는
이름으로 부름.


빠짐없이 대응이 정의된 함수를 전함수(total function)라고도 부름.
그냥 함수라고 하면 전함수를 뜻함. 참고로 전함수도 부분함수임.
일대일 조건을 만족하는 게 부분함수의 정의이므로, 다른 조건을 좀더
만족한다고 해서 정의상 부분함수가 아니게 되는 것은 아니다.

함수의 리턴값이 진리값(참 또는 거짓)인 함수를 불리언 함수(boolean function)라고
부르지만 predicate(술어) 또는 proerty(성질)이라고도 부름.


그냥 집합 2개 $A$와 $B$ 사이의 관계(relation)는 $A times B$의 부분집합이면 아무거나 됨.

함수와 관계의 항수(arity)
- $k$항 함수($k$-ary function) $f: A_1 times A_2 times ... times A_k arrow B$에
  넘겨주는 값들의 집합이 \ $A_1 times A_2 times ... times A_k$로 $k$개의 곱집합.
  마지막 공역(codomain) $B$는 항수를 따질 때 포함 안됨.
- $k$항 관계($k$-ary relation) $R subset.eq A_1 times A_2 times ... times A_k$은
  마지막까지 총 $k$개 곱집합의 부분집합

$k$항 함수는 ($k$항 관계가 아니라) $k+1$항 관계의 특별한 경우.

헷갈리지 않도록 주의!!!
$k$항 관계인지 검사하는 함수(즉, predicate / property)의 항수는 $k$다.
주어진 $k$-tuple이
$k$항 관계 $R subset.eq A_1 times A_2 times ... times A_k$를 만족하나
검사(즉, 진리값을 리턴)하는 함수
$p: A_1 times A_2 times ... times A_k arrow cal(B)$의 정의는 다음과 같다.
(단, $cal(B) = {sc("true"), sc("false")}$)

#[
#set math.equation(numbering: none)
$ p(a_1, a_2, ..., a_k) = cases(
      sc("true") thin quad (a_1, a_2, ..., a_k) in R,
      sc("false")     quad (a_1, a_2, ..., a_k) in.not R,
) $
]


#heading(level: 2, numbering: none)[관계의 표기법]
관계 $R subset.eq A times B$에서 일반적으로는
- $(a,b) in R$이면 $R(a,b)$로 표기
- $(a,b) in.not R$이면 $not R(a,b)$로 표기

위의 표기법은 항수에 관계없이 활용 가능

특별히 항수(arity)가 2인, 즉 이항 관계(binary relation)일 때는\
중위(infix) 표기법도 활용 가능함
- $(a,b) in R$이면 $a thin R thin b$로 표기
- $(a,b) in.not R$이면 $not(a thin R thin b)$
  또는 $a thin #math.class("relation", $R\u{0338}$) thin b$ 등으로 표기
































